# Generated by Django 4.2.6 on 2023-10-29 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTableComment(
            name='cat',
            table_comment='Информация о кошках и их хозяева',
        ),
    ]
