# Generated by Django 4.2.6 on 2023-10-29 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0002_alter_cat_table_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cat',
            options={'verbose_name': 'Cat', 'verbose_name_plural': 'Cats'},
        ),
        migrations.AlterModelTableComment(
            name='cat',
            table_comment=None,
        ),
    ]
