# Generated by Django 4.2.6 on 2023-10-29 20:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0003_alter_cat_options_alter_cat_table_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat',
            name='birth_year',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(1993)]),
        ),
    ]
